#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_CAPS, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, RALT(KC_Q), KC_TAB, LALT_T(KC_A), LCTL_T(KC_S), LGUI_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RGUI_T(KC_K), RCTL_T(KC_L), RALT_T(KC_SCLN), RALT(KC_P), KC_DEL, KC_Z, KC_X, KC_C, KC_V, KC_B, TT(2), KC_NO, KC_NO, TT(2), KC_N, KC_M, KC_COMM, KC_DOT, KC_QUES, RALT(KC_Y), LCTL(KC_W), TG(3), TT(1), KC_BSPC, KC_ESC, KC_ENT, KC_SPC, TT(1), TG(4), LCTL(KC_T)),
	[1] = LAYOUT(KC_P0, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_PPLS, KC_PMNS, KC_PEQL, KC_PLUS, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_PAST, KC_PSLS, KC_CIRC, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_P0, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_F24, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE),
	[2] = LAYOUT(KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_LPRN, KC_RPRN, KC_NO, KC_QUOT, KC_TRNS, KC_NO, KC_PSLS, KC_PIPE, KC_BSLS, KC_UNDS, KC_NO, KC_NO, KC_LCBR, KC_RCBR, KC_TRNS, KC_DQUO, KC_TRNS, KC_NO, KC_NO, KC_NO, RALT(KC_5), KC_TILD, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_TRNS, KC_GRV, LGUI(KC_F), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_SPC)),
	[3] = LAYOUT(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_WH_D, KC_WH_U, KC_F9, KC_F10, KC_F11, KC_NO, KC_NO, KC_BTN3, KC_BTN2, KC_BTN1, KC_HOME, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_PGUP, KC_F12, KC_NO, KC_NO, KC_MPRV, KC_MPLY, KC_MNXT, KC_END, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_PGDN, KC_PSCR, KC_BTN1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN3),
	[4] = LAYOUT(KC_NO, RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, RGB_M_T, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, KC_NO, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI, RGB_SPI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_TRNS, RGB_RMOD, RGB_HUD, RGB_SAD, RGB_VAD, RGB_SPD, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO)
};

bool encoder_update_user(uint8_t index, bool clockwise) {
	if (index == 0) { // left encoder
		switch(biton32(layer_state)){
			case 3:
				if (clockwise) {
					tap_code(KC_LEFT);
				} else {
					tap_code(KC_RIGHT);
				}
				break;
			case 2:
				if (clockwise) {
					tap_code16(G(KC_J));
				} else {
					tap_code16(G(KC_K));
				}
				break;
			case 1:
				if (clockwise) {
					tap_code(KC_BRIU);
				} else {
					tap_code(KC_BRID);
				}
				break;
			default:
				if (clockwise) {
					tap_code16(S(C(KC_TAB)));
				} else {
					tap_code16(C(KC_TAB));
				}
				break;
		}
	}
	else if (index == 1) { // right encoder
		switch(biton32(layer_state)){
			case 3:
				if (clockwise) {
					tap_code(KC_UP);
				} else {
					tap_code(KC_DOWN);
				}
				break;
			case 2:
				if (clockwise) {
					tap_code16(G(KC_H));
				} else {
					tap_code16(G(KC_L));
				}
				break;
			case 1:
				if (clockwise) {
					tap_code(KC_VOLU);
				} else {
					tap_code(KC_VOLD);
				}
				break;
			default:
				if (clockwise) {
					tap_code(KC_PGUP);
				} else {
					tap_code(KC_PGDN);
				}
				break;
		}
	}
	return false;
}
